index:
    path: /
    controller: App\Controller\AccountController::index

login:
    path: /login
    controller: App\Controller\AccountController::login

logout:
    path: /logout
    controller: App\Controller\AccountController::logout

home:
    path: /home
    controller: App\Controller\PageController::home

properties:
    path: /properties
    controller: App\Controller\PageController::properties

properties_create:
    path: /properties/create
    controller: App\Controller\Property\PropertyController::add
    methods: POST

properties_update:
    path: /properties/edit
    controller: App\Controller\Property\PropertyController::update
    methods: POST

properties_delete:
    path: /properties/delete
    controller: App\Controller\Property\PropertyController::ban
    methods: POST