index:
    path: /
    controller: App\Controller\AccountController::index

login:
    path: /login
    controller: App\Controller\AccountController::login

logout:
    path: /logout
    controller: App\Controller\AccountController::logout

home:
    path: /home
    controller: App\Controller\PageController::home